version: "3.8"

services:

  frontend: 
    container_name: frontend-dev
    image: moonbot-frontend-image-dev
    build:
      context: ./frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src