# Generated by Django 3.2.9 on 2021-11-15 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='BC_day',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='cries',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1008), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='energy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
