# Generated by Django 3.2.9 on 2021-11-15 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0002_auto_20211115_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cries',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MinValueValidator(1008)]),
        ),
    ]
