# Generated by Django 3.2.9 on 2021-11-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sleep',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='entry',
            name='wake',
            field=models.CharField(default='', max_length=5),
        ),
    ]
