# Generated by Django 3.2.9 on 2021-11-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0004_alter_entry_cries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='day',
            field=models.DateTimeField(null=True),
        ),
    ]
