# Generated by Django 3.2.9 on 2021-11-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0004_entry_datestring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
    ]
