# Generated by Django 3.2.9 on 2021-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0005_entry_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
