# Generated by Django 3.2.9 on 2021-11-12 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0005_remove_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='energy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
