# Generated by Django 3.2.9 on 2021-11-12 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0006_entry_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cries',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(-1), django.core.validators.MinValueValidator(1008)]),
        ),
    ]
