# Generated by Django 3.2.9 on 2021-11-15 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0006_auto_20211115_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dayInMilliseconds',
            field=models.PositiveBigIntegerField(default=1636956000000, validators=[django.core.validators.MaxValueValidator(35185644000000)]),
            preserve_default=False,
        ),
    ]
