# Generated by Django 3.2.9 on 2021-11-12 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0007_entry_cries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='BC_day',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(31)]),
        ),
    ]
