# Generated by Django 3.2.9 on 2021-11-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0007_entry_dayinmilliseconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='timestamp',
        ),
    ]
