# Generated by Django 3.2.9 on 2021-11-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0008_remove_entry_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='updatedAt',
        ),
    ]
