# Generated by Django 3.2.9 on 2021-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0008_entry_bc_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sleepDomain',
            field=models.CharField(default='pm', max_length=2),
        ),
        migrations.AddField(
            model_name='entry',
            name='wakeDomain',
            field=models.CharField(default='am', max_length=2),
        ),
    ]
