# Generated by Django 3.2.9 on 2021-11-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0009_remove_entry_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
