# Generated by Django 3.2.9 on 2021-11-14 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0009_auto_20211114_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rest',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='restCalculated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
