# Generated by Django 3.2.9 on 2021-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0010_auto_20211114_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='restCalculated',
            field=models.BooleanField(default=False),
        ),
    ]
