# Generated by Django 3.2.9 on 2021-11-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0010_remove_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='day',
        ),
    ]
