# Generated by Django 3.2.9 on 2021-11-16 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0011_remove_entry_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='energy',
            new_name='energy_evening',
        ),
        migrations.AddField(
            model_name='entry',
            name='energy_midday',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='energy_morning',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
