# Generated by Django 3.2.9 on 2021-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0011_alter_entry_restcalculated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='restCalculated',
            new_name='rest_calculated',
        ),
        migrations.AlterField(
            model_name='entry',
            name='rest',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
