# Generated by Django 3.2.9 on 2021-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0012_auto_20211116_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_bc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='display_cry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='display_energy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='display_outside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='display_rest',
            field=models.BooleanField(default=False),
        ),
    ]
