# Generated by Django 3.2.9 on 2021-11-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astral', '0013_auto_20211116_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_cry',
        ),
        migrations.AddField(
            model_name='user',
            name='display_cries',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_bc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_energy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_rest',
            field=models.BooleanField(default=True),
        ),
    ]
